### ISSUE TITLE
Needs some way to create a randomizer seed

### ISSUE THREAD

**Issue by voronoipotato** [hasherezade/password_scrambler#7]
Right now if enough people were to use this, people could use it to crack passwords. With an account wide randomizer seed like an ssh key or passphrase the ability to use it to get passwords approaches zero.

**Comment by voronoipotato** [comment]
Ah, reading this I didn't notice that it takes a file and that the file is required for seed generation. This makes more sense. Apologies!

**Comment by hasherezade** [comment]
Exactly, that's why the file is important -you could brutforce the short password, i.e. using a dictionary, but to recreate someone's seed file is _very_ hard (impossible?). if you steal the file, then yes, you can brutforce the password. but if the machine is trojanized, it is easier to steal the password from the clipboard.

**Comment by hasherezade** [comment]
additionally, you can make brutforcing more difficult by supplying the login in your own custom format, that would be unexpected for the person trying to brutforce. i.e.
Assuming my account is `test@gmail.com`, I can generate my password like this:
```
./passcrambler.py --file LICENSE --login test@gmail.com
Password: test123
---
5SV60BGrSgwDJKWikk2CNa_7WcFUtk
---
```
or like this:
```
./passcrambler.py --file LICENSE --login test%gmail.com%salt
Password: test123
---
eassz_zb&riDCimKRt8kV6iAxX0RpY
---
```
or like this:
```
./passcrambler.py --file LICENSE --login MY_SALT_test@gmail.com
Password: test123
---
lqAHqi_WfM2tVypbNRZDWlh&zAPtpf
---
```
In all those cases the doc is the same [LICENSE](https://github.com/hasherezade/password_scrambler/blob/8a781ad42f0da3d9a17e3c9acb7d8736051400ff/LICENSE), the short password is the same: `test123`, yet the output is completely different. So, in order to brutforce, the attacked must have your file and must know your format.

**Comment by hasherezade** [comment]
BTW - if you have any more questions/remarks about this, feel free to share, otherwise you can close this issue.

**Comment by voronoipotato** [comment]
Can I generate passwords with only providing a login and a file?

**Comment by hasherezade** [comment]
Yes, you can, however I don't recommend, because the short pass gives it an additional factor. Also, then, in order to change the password you will have to change the file. And if you have the short password, you can only add a character to it, and you get a different output.
i.e. for short pass `test123`
```
./passcrambler.py --file LICENSE --login test@gmail.com
Password: test123
---
5SV60BGrSgwDJKWikk2CNa_7WcFUtk
---
```
vs short pass `test1234`
```
./passcrambler.py --file LICENSE --login test@gmail.com
Password: test1234
---
V0CqLilIL5Ckc2F2ziX_9pGhLorbMC
---
```

**Comment by hasherezade** [comment]
Also, some random ideas to make it more secure: 
+ having an isolated environment to store the generator and the related files (a separate VM?)
+ maybe keeping the seed file in a secure vault, and decrypting it only on demand? 
+ auto-cleaning the password from the clipboard after the timeout?

For now I my goal was to make a minimalistic tool (sorta prototype of the core idea). But for sure there is a space for improvements: if there will be a public interest, I will be thinking how to improve it.

**Comment by voronoipotato** [comment]
Essentially the file becomes the password. Kinda like passwordless SSH keys. it's not ... ideal security but it's probably a lot better than what I do now.
